
--TEST QUERY WITH A BITMAP INDEX
SELECT  *  FROM a_product WHERE product_name = 'Socks' AND product_size LIKE '%S%' ORDER BY 1 DESC;

--CREATE BITMAP INDEX ON ROW HAVING LOW CARDINALITY (It MEANS FEW RECORDS DIFFERENCE)
CREATE BITMAP INDEX INDEX1 ON A_PRODUCT (PRODUCT_NAME ASC, PRODUCT_SIZE) 
TABLESPACE ALAIN_SPACE;

--CREATE UNIQUE ON PRIMARY KEY is NOT POSSIBLE ON ORACLE
--CREATE UNIQUE INDEX INDEX1 ON A_PRODUCT (PRODUCT_ID ASC) 
--TABLESPACE ALAIN_SPACE;

--DROP BITMAP INDEX
drop index "ALAIN"."INDEX1"
